; Path to your Dark Souls 3 game directory.
game_path=C:\Program Files (x86)\Steam\steamapps\common\DARK SOULS III\Game
; Path to your Dark Souls 3 mod directory.
mod_path=C:\Program Files (x86)\Steam\steamapps\common\DARK SOULS III\Game\my_mod
; Path to your local mod textures directory.
tex_path=C:\Program Files (x86)\Steam\steamapps\common\DARK SOULS III\Game\my_textures